apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
  labels:
    role: todo-frontend
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: todo-frontend
  template:
    metadata:
      labels:
        role: todo-frontend
    spec: 
      containers:
      - name: todo-frontend
        image: mukeshr29/todo-frontend:latest
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "a0c87f30da91d4ca989d9bb7582b1e9d-1046882023.us-east-1.elb.amazonaws.com/todo-backend/tasks"
        ports:
        - containerPort: 3000